name: Check One File Commit

on: [push]

jobs:
  verify-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check that b.txt exists
        run: |
          if [ ! -f "b.txt" ]; then
            echo "❌ b.txt is missing."
            exit 1
          else
            echo "✅ b.txt is present."
          fi

      - name: Check that a.txt does NOT exist
        run: |
          if [ -f "a.txt" ]; then
            echo "❌ a.txt should not be present."
            exit 1
          else
            echo "✅ a.txt is not present."
          fi